# Generated by Django 4.2.3 on 2023-08-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgeditor', '0005_alter_imagefile_processed_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='compressed_img',
            field=models.ImageField(blank=True, null=True, upload_to='compressed/'),
        ),
    ]
