# Generated by Django 4.2.3 on 2023-08-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgeditor', '0006_imagefile_compressed_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='filtered_img',
            field=models.ImageField(blank=True, null=True, upload_to='filtered/'),
        ),
    ]
